import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Importa il componente AuthProvider
import AuthProvider from "@/components/admin-panel/AuthProvider";

// Importa il componente principale dell'applicazione App
import App from "./App";

// Definizione del font Inter con subset latino
const inter = Inter({ subsets: ["latin"] });

// Metadati dell'applicazione
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Componente RootLayout: layout principale dell'applicazione
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Avvolge l'App principale con AuthProvider */}
        <AuthProvider>
          {/* Renderizza l'App e i componenti figli passati come props */}
          <App>
            {children}
          </App>
        </AuthProvider>
      </body>
    </html>
  );
}
